# Generated by Django 5.2.7 on 2025-10-20 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialValidacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('tipo_validacion', models.CharField(choices=[('abastecimiento_lambda', 'Abastecimiento Lambda'), ('finanzas_lambda', 'Finanzas Lambda'), ('pago', 'Validación de Pago'), ('facturacion', 'Facturación')], max_length=30, verbose_name='Tipo de Validación')),
                ('accion', models.CharField(choices=[('aprobar', 'Aprobado'), ('rechazar', 'Rechazado'), ('modificar', 'Modificado'), ('pago_confirmado', 'Pago Confirmado'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('asignar_area', 'Asignado a Área'), ('asignacion_area', 'Asignación de Área Lambda')], max_length=20, verbose_name='Acción')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, help_text='Snapshot del estado anterior', verbose_name='Datos Anteriores')),
                ('monto_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto del Pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de Pago')),
                ('area_asignada', models.CharField(blank=True, help_text='Área Lambda a la que se asignó el pedido', max_length=20, null=True, verbose_name='Área Asignada')),
            ],
            options={
                'verbose_name': 'Historial de Validación de Pedido',
                'verbose_name_plural': 'Historial de Validaciones de Pedidos',
                'db_table': 'historial_validaciones_pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('cantidad_aprobada_cliente', models.PositiveIntegerField(verbose_name='Cantidad Aprobada por Cliente')),
                ('cantidad_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Final Aprobada por Lambda')),
                ('precio_unitario_solicitud', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario en Solicitud')),
                ('precio_unitario_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario Final Lambda')),
                ('observaciones_lambda', models.TextField(blank=True, null=True, verbose_name='Observaciones de Lambda')),
                ('stock_reservado', models.BooleanField(default=False, verbose_name='Stock Reservado')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'db_table': 'items_pedido',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('numero_pedido', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('estado', models.CharField(choices=[('pendiente_validacion_lambda', 'Pendiente Validación Lambda'), ('pendiente_abastecimiento_lambda', 'Pendiente Área Abastecimiento Lambda'), ('pendiente_finanzas_lambda', 'Pendiente Área Finanzas Lambda'), ('aprobado_lambda', 'Aprobado por Lambda'), ('rechazado_abastecimiento_lambda', 'Rechazado por Abastecimiento Lambda'), ('rechazado_finanzas_lambda', 'Rechazado por Finanzas Lambda'), ('pendiente_pago', 'Pendiente de Pago'), ('pago_confirmado', 'Pago Confirmado'), ('pago_vencido', 'Pago Vencido'), ('facturado', 'Facturado'), ('cancelado', 'Cancelado')], default='pendiente_validacion_lambda', max_length=40, verbose_name='Estado del Pedido')),
                ('observaciones_cliente', models.TextField(blank=True, null=True, verbose_name='Observaciones del Cliente')),
                ('fecha_validacion_abastecimiento_lambda', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Abastecimiento Lambda')),
                ('comentario_abastecimiento_lambda', models.TextField(blank=True, null=True, verbose_name='Comentario Abastecimiento Lambda')),
                ('stock_confirmado_lambda', models.BooleanField(default=False, verbose_name='Stock Confirmado en Lambda')),
                ('fecha_validacion_finanzas_lambda', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Finanzas Lambda')),
                ('comentario_finanzas_lambda', models.TextField(blank=True, null=True, verbose_name='Comentario Finanzas Lambda')),
                ('credito_aprobado_lambda', models.BooleanField(default=False, verbose_name='Crédito Aprobado por Lambda')),
                ('modalidad_pago', models.CharField(blank=True, choices=[('inmediato', 'Pago Inmediato'), ('diferido', 'Pago Diferido')], max_length=20, null=True, verbose_name='Modalidad de Pago')),
                ('fecha_limite_pago', models.DateField(blank=True, null=True, verbose_name='Fecha Límite de Pago')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Total')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento Aplicado (%)')),
                ('monto_final', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto Final a Pagar')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Facturación')),
                ('comprobante_pago', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Comprobante de Pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de Pago')),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Despacho')),
                ('numero_guia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Guía de Despacho')),
                ('transportadora', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa Transportadora')),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada de Entrega')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Entrega')),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Factura')),
                ('fecha_factura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Facturación')),
                ('factura_enviada', models.BooleanField(default=False, verbose_name='Factura Enviada por Correo')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedidos',
                'ordering': ['-created_at'],
                'permissions': [('puede_validar_pedido_abastecimiento_lambda', 'Puede validar pedidos (Abastecimiento Lambda)'), ('puede_validar_pedido_finanzas_lambda', 'Puede validar pedidos (Finanzas Lambda)'), ('puede_aprobar_pedido_lambda', 'Puede aprobar pedidos finales Lambda'), ('puede_gestionar_pagos', 'Puede gestionar pagos de pedidos'), ('puede_gestionar_despachos', 'Puede gestionar despachos'), ('puede_ver_todos_pedidos', 'Puede ver todos los pedidos')],
            },
        ),
        migrations.CreateModel(
            name='RecordatorioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('tipo', models.CharField(choices=[('preventivo', 'Recordatorio Preventivo (3 días antes)'), ('vencimiento', 'Recordatorio de Vencimiento'), ('mora_1', 'Primer Recordatorio de Mora (15 días)'), ('mora_2', 'Segundo Recordatorio de Mora (30 días)'), ('mora_3', 'Tercer Recordatorio de Mora (45 días)'), ('mora_4', 'Cuarto Recordatorio de Mora (60 días)'), ('legal', 'Notificación Legal (75 días)')], max_length=20, verbose_name='Tipo de Recordatorio')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada de Envío')),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('email_destinatario', models.EmailField(max_length=254, verbose_name='Email Destinatario')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto del Correo')),
                ('exitoso', models.BooleanField(blank=True, null=True, verbose_name='Envío Exitoso')),
                ('error_envio', models.TextField(blank=True, null=True, verbose_name='Error de Envío')),
            ],
            options={
                'verbose_name': 'Recordatorio de Pago',
                'verbose_name_plural': 'Recordatorios de Pago',
                'db_table': 'recordatorios_pago',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
