# Generated by Django 5.2.7 on 2025-10-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_initial'),
        ('Pedidos', '0001_initial'),
        ('Productos', '0002_initial'),
        ('Solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialvalidacionpedido',
            name='validador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_pedidos_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_pedido', to='Productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Empresas.empresa', verbose_name='Empresa Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitud_origen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='Solicitudes.solicitud', verbose_name='Solicitud de Origen'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='validador_abastecimiento_lambda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_validados_abastecimiento_lambda', to=settings.AUTH_USER_MODEL, verbose_name='Validador Abastecimiento Lambda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='validador_finanzas_lambda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_validados_finanzas_lambda', to=settings.AUTH_USER_MODEL, verbose_name='Validador Finanzas Lambda'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='historialvalidacionpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_validaciones', to='Pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='recordatoriopago',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='Pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterUniqueTogether(
            name='itempedido',
            unique_together={('pedido', 'producto')},
        ),
        migrations.AlterUniqueTogether(
            name='recordatoriopago',
            unique_together={('pedido', 'tipo')},
        ),
    ]
