# Generated by Django 5.2.7 on 2025-10-17 16:13

import Usuarios.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de celular')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('estado', models.CharField(choices=[('pendiente_activacion', 'Pendiente de Activación'), ('activo', 'Activo'), ('inactivo', 'Inactivo')], default='pendiente_activacion', max_length=30, verbose_name='Estado')),
                ('token_activacion', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True, verbose_name='Token de activación')),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de activación')),
                ('is_active', models.BooleanField(default=False, verbose_name='Usuario activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('es_primer_usuario', models.BooleanField(default=False, help_text='True si es el primer usuario creado para la empresa', verbose_name='Es primer usuario')),
                ('permisos_personalizados', models.JSONField(blank=True, default=dict, help_text='Permisos dinámicos: validadores, límites, etc.', verbose_name='Permisos especiales')),
                ('area', models.ForeignKey(blank=True, help_text='Área funcional dentro de la empresa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='Empresas.area', verbose_name='Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece (null para usuarios de Lambda)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Empresas.empresa', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-created_at'],
                'permissions': [('puede_crear_usuarios', 'Puede crear usuarios'), ('puede_editar_usuarios', 'Puede editar usuarios'), ('puede_eliminar_usuarios', 'Puede eliminar usuarios'), ('puede_activar_usuarios', 'Puede activar/desactivar usuarios'), ('puede_asignar_areas', 'Puede asignar áreas a usuarios'), ('puede_asignar_roles', 'Puede asignar roles a usuarios'), ('puede_ver_todos_usuarios', 'Puede ver todos los usuarios'), ('puede_crear_solicitudes', 'Puede crear solicitudes internas'), ('puede_editar_solicitudes', 'Puede editar solicitudes propias'), ('puede_ver_solicitudes_propias', 'Puede ver sus propias solicitudes'), ('puede_ver_solicitudes_area', 'Puede ver solicitudes de su área'), ('puede_ver_todas_solicitudes', 'Puede ver todas las solicitudes'), ('puede_validar_abastecimiento', 'Puede validar solicitudes (Abastecimiento)'), ('puede_validar_finanzas', 'Puede validar solicitudes (Finanzas)'), ('puede_aprobar_pedidos', 'Puede aprobar pedidos finales'), ('puede_rechazar_pedidos', 'Puede rechazar pedidos'), ('puede_ver_catalogo', 'Puede ver catálogo de productos'), ('puede_ver_precios', 'Puede ver precios de productos'), ('puede_solicitar_productos', 'Puede solicitar productos'), ('puede_ver_reportes_basicos', 'Puede ver reportes básicos'), ('puede_ver_reportes_avanzados', 'Puede ver reportes avanzados'), ('puede_exportar_reportes', 'Puede exportar reportes')],
            },
        ),
        migrations.CreateModel(
            name='ActivacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField(default=Usuarios.models.fecha_expiracion_default)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activación de usuario',
                'verbose_name_plural': 'Activaciones de usuarios',
                'db_table': 'activaciones_usuarios',
            },
        ),
    ]
