# Generated by Django 5.2.7 on 2025-10-07 16:31

import Usuarios.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('celular', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de celular')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Empresas.area', verbose_name='Área')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='Empresas.empresa', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['empresa', 'nombres'],
                'permissions': [('es_admin_empresa', 'Es Administrador de Empresa'), ('valida_financiero', 'Validador Financiero'), ('valida_logistica', 'Validador Logística'), ('valida_venta', 'Validador de Ventas')],
            },
        ),
        migrations.CreateModel(
            name='ActivacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField(default=Usuarios.models.fecha_expiracion_default)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activación de usuario',
                'verbose_name_plural': 'Activaciones de usuarios',
                'db_table': 'activaciones_usuarios',
            },
        ),
    ]
