# Generated by Django 5.2.7 on 2025-10-20 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Configuración')),
                ('tipo_reporte', models.CharField(choices=[('ventas_mensual', 'Ventas Mensual'), ('ventas_anual', 'Ventas Anual'), ('empresas_mensual', 'Por Empresa Mensual'), ('productos_mensual', 'Por Productos Mensual'), ('pagos_pendientes', 'Pagos Pendientes'), ('mora_empresas', 'Empresas en Mora')], max_length=50, verbose_name='Tipo de Reporte')),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('emails_destino', models.JSONField(default=list, help_text='Lista de emails que recibirán el reporte', verbose_name='Emails de Destino')),
                ('proxima_ejecucion', models.DateTimeField(verbose_name='Próxima Ejecución')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'db_table': 'reportes_configuracion',
            },
        ),
        migrations.CreateModel(
            name='ItemFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
                'db_table': 'reportes_item_factura',
            },
        ),
        migrations.CreateModel(
            name='ReportePeriodico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Reporte')),
                ('tipo', models.CharField(choices=[('ventas_mensual', 'Ventas Mensual'), ('ventas_anual', 'Ventas Anual'), ('empresas_mensual', 'Por Empresa Mensual'), ('productos_mensual', 'Por Productos Mensual'), ('pagos_pendientes', 'Pagos Pendientes'), ('mora_empresas', 'Empresas en Mora')], max_length=50, verbose_name='Tipo de Reporte')),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=20, verbose_name='Formato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/', verbose_name='Archivo Generado')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('total_registros', models.IntegerField(default=0, verbose_name='Total de Registros')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Total')),
                ('resumen_json', models.JSONField(default=dict, verbose_name='Resumen en JSON')),
            ],
            options={
                'verbose_name': 'Reporte Periódico',
                'verbose_name_plural': 'Reportes Periódicos',
                'db_table': 'reportes_periodico',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('numero_factura', models.CharField(help_text='Generado automáticamente: FACT-YYYY-NNNNNN', max_length=50, unique=True, verbose_name='Número de Factura')),
                ('tipo', models.CharField(choices=[('venta', 'Factura de Venta'), ('nota_credito', 'Nota de Crédito'), ('nota_debito', 'Nota de Débito')], default='venta', max_length=20, verbose_name='Tipo de Factura')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('enviada', 'Enviada al Cliente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento Aplicado')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuestos (IVA)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Factura')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdf/', verbose_name='Archivo PDF')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('terminos_condiciones', models.TextField(blank=True, verbose_name='Términos y Condiciones')),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='Empresas.empresa', verbose_name='Empresa Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'reportes_factura',
                'ordering': ['-fecha_emision', '-numero_factura'],
            },
        ),
    ]
