# Generated by Django 5.2.7 on 2025-10-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_initial'),
        ('Pedidos', '0002_initial'),
        ('Reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='generada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Generada por'),
        ),
        migrations.AddField(
            model_name='factura',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='Pedidos.pedido', verbose_name='Pedido Asociado'),
        ),
        migrations.AddField(
            model_name='itemfactura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Reportes.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='reporteperiodico',
            name='empresa_filtro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresas.empresa', verbose_name='Filtrar por Empresa'),
        ),
        migrations.AddField(
            model_name='reporteperiodico',
            name='generado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
    ]
