# Generated by Django 5.2.7 on 2025-10-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de stock'), ('SALIDA', 'Salida por despacho'), ('RESERVA', 'Reserva de stock'), ('LIBERACION', 'Liberación de reserva'), ('AJUSTE', 'Ajuste de inventario')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción/Comprobante')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock_fisico', models.PositiveIntegerField(default=0, verbose_name='Stock Físico Total')),
                ('stock_reservado', models.PositiveIntegerField(default=0, verbose_name='Stock Reservado')),
                ('umbral_minimo', models.PositiveIntegerField(default=5, verbose_name='Umbral mínimo de stock')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
    ]
