# Generated by Django 5.2.7 on 2025-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado_aprobacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evento de aprobación',
                'verbose_name_plural': 'Historial de aprobaciones',
                'db_table': 'historial_aprobaciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='ProductoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Producto solicitado',
                'verbose_name_plural': 'Productos solicitados',
                'db_table': 'productos_solicitud',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('justificacion', models.TextField(verbose_name='Justificación de la solicitud')),
                ('estado', models.CharField(choices=[('pendiente_abastecimiento', 'Pendiente Abastecimiento'), ('pendiente_finanzas', 'Pendiente Finanzas'), ('rechazada', 'Rechazada'), ('aprobada', 'Aprobada')], default='pendiente_abastecimiento', max_length=50)),
            ],
            options={
                'verbose_name': 'Solicitud interna',
                'verbose_name_plural': 'Solicitudes internas',
                'db_table': 'solicitudes',
                'ordering': ['-creado'],
            },
        ),
    ]
