# Generated by Django 5.2.7 on 2025-10-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_initial'),
        ('Productos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('numero_solicitud', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Solicitud')),
                ('justificacion', models.TextField(verbose_name='Justificación de la solicitud')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_abastecimiento', 'Pendiente Abastecimiento'), ('rechazada_abastecimiento', 'Rechazada por Abastecimiento'), ('pendiente_finanzas', 'Pendiente Finanzas'), ('rechazada_finanzas', 'Rechazada por Finanzas'), ('aprobada', 'Aprobada - Lista para Compra'), ('convertida_pedido', 'Convertida a Pedido'), ('cancelada', 'Cancelada')], default='pendiente_abastecimiento', max_length=30, verbose_name='Estado')),
                ('fecha_validacion_abastecimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Abastecimiento')),
                ('comentario_abastecimiento', models.TextField(blank=True, null=True, verbose_name='Comentario de Abastecimiento')),
                ('stock_validado', models.BooleanField(default=False, verbose_name='Stock Validado')),
                ('fecha_validacion_finanzas', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Finanzas')),
                ('comentario_finanzas', models.TextField(blank=True, null=True, verbose_name='Comentario Financiero')),
                ('presupuesto_aprobado', models.BooleanField(default=False, verbose_name='Presupuesto Aprobado')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Total')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Empresas.empresa', verbose_name='Empresa')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
                ('validador_abastecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validadas_abastecimiento', to=settings.AUTH_USER_MODEL, verbose_name='Validador de Abastecimiento')),
                ('validador_finanzas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validadas_finanzas', to=settings.AUTH_USER_MODEL, verbose_name='Validador Financiero')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-created_at'],
                'permissions': [('puede_validar_solicitud_abastecimiento', 'Puede validar solicitudes (Abastecimiento)'), ('puede_validar_solicitud_finanzas', 'Puede validar solicitudes (Finanzas)'), ('puede_aprobar_solicitud', 'Puede aprobar solicitudes finales'), ('puede_rechazar_solicitud', 'Puede rechazar solicitudes')],
            },
        ),
        migrations.CreateModel(
            name='HistorialValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('tipo_validacion', models.CharField(choices=[('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas')], max_length=20, verbose_name='Tipo de Validación')),
                ('accion', models.CharField(choices=[('aprobar', 'Aprobado'), ('rechazar', 'Rechazado'), ('modificar', 'Modificado')], max_length=20, verbose_name='Acción')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, help_text='Snapshot del estado anterior', verbose_name='Datos Anteriores')),
                ('validador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_validaciones', to='Solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Historial de Validación',
                'verbose_name_plural': 'Historial de Validaciones',
                'db_table': 'historial_validaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('cantidad_aprobada', models.PositiveIntegerField(blank=True, help_text='Cantidad final aprobada por Abastecimiento', null=True, verbose_name='Cantidad Aprobada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_solicitud', to='Productos.producto', verbose_name='Producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Solicitudes.solicitud', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
                'db_table': 'items_solicitud',
                'unique_together': {('solicitud', 'producto')},
            },
        ),
    ]
