# Generated by Django 5.2.7 on 2025-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('tipo_validacion', models.CharField(choices=[('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas')], max_length=20, verbose_name='Tipo de Validación')),
                ('accion', models.CharField(choices=[('aprobar', 'Aprobado'), ('rechazar', 'Rechazado'), ('modificar', 'Modificado')], max_length=20, verbose_name='Acción')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('datos_anteriores', models.JSONField(blank=True, default=dict, help_text='Snapshot del estado anterior', verbose_name='Datos Anteriores')),
            ],
            options={
                'verbose_name': 'Historial de Validación',
                'verbose_name_plural': 'Historial de Validaciones',
                'db_table': 'historial_validaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('cantidad_aprobada', models.PositiveIntegerField(blank=True, help_text='Cantidad final aprobada por Abastecimiento', null=True, verbose_name='Cantidad Aprobada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Item de Solicitud',
                'verbose_name_plural': 'Items de Solicitud',
                'db_table': 'items_solicitud',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('numero_solicitud', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Número de Solicitud')),
                ('justificacion', models.TextField(verbose_name='Justificación de la solicitud')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_jefe_area', 'Pendiente Aprobación Jefe de Área'), ('rechazada_jefe_area', 'Rechazada por Jefe de Área'), ('pendiente_abastecimiento', 'Pendiente Abastecimiento'), ('rechazada_abastecimiento', 'Rechazada por Abastecimiento'), ('pendiente_finanzas', 'Pendiente Finanzas'), ('rechazada_finanzas', 'Rechazada por Finanzas'), ('aprobada', 'Aprobada - Lista para Conversión'), ('convertida_pedido', 'Convertida a Pedido'), ('cancelada', 'Cancelada')], default='pendiente_jefe_area', max_length=30, verbose_name='Estado')),
                ('fecha_aprobacion_jefe', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Aprobación Jefe')),
                ('comentario_jefe', models.TextField(blank=True, null=True, verbose_name='Comentario del Jefe de Área')),
                ('fecha_validacion_abastecimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Abastecimiento')),
                ('comentario_abastecimiento', models.TextField(blank=True, null=True, verbose_name='Comentario de Abastecimiento')),
                ('stock_validado', models.BooleanField(default=False, verbose_name='Stock Validado')),
                ('fecha_validacion_finanzas', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación Finanzas')),
                ('comentario_finanzas', models.TextField(blank=True, null=True, verbose_name='Comentario Financiero')),
                ('presupuesto_aprobado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Aprobado')),
                ('forma_pago_preferida', models.CharField(choices=[('inmediato', 'Pago Inmediato'), ('credito', 'Pago a Crédito'), ('diferido', 'Pago Diferido')], default='inmediato', max_length=20, verbose_name='Forma de Pago Preferida')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Total')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'db_table': 'solicitudes',
                'ordering': ['-created_at'],
                'permissions': [('puede_validar_solicitud_abastecimiento', 'Puede validar solicitudes (Abastecimiento)'), ('puede_validar_solicitud_finanzas', 'Puede validar solicitudes (Finanzas)'), ('puede_aprobar_solicitud', 'Puede aprobar solicitudes finales'), ('puede_rechazar_solicitud', 'Puede rechazar solicitudes')],
            },
        ),
    ]
