# Generated by Django 5.2.7 on 2025-10-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0002_initial'),
        ('Productos', '0003_initial'),
        ('Solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialvalidacion',
            name='validador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Validador'),
        ),
        migrations.AddField(
            model_name='itemsolicitud',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_solicitud', to='Productos.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='Empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='jefe_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas_jefe', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Área que Aprueba'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='validador_abastecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validadas_abastecimiento', to=settings.AUTH_USER_MODEL, verbose_name='Validador de Abastecimiento'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='validador_finanzas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_validadas_finanzas', to=settings.AUTH_USER_MODEL, verbose_name='Validador Financiero'),
        ),
        migrations.AddField(
            model_name='itemsolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Solicitudes.solicitud', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='historialvalidacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_validaciones', to='Solicitudes.solicitud', verbose_name='Solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsolicitud',
            unique_together={('solicitud', 'producto')},
        ),
    ]
