# Generated by Django 5.2.7 on 2025-10-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del área')),
                ('tipo', models.CharField(choices=[('operativa', 'Área Operativa'), ('financiera', 'Área Financiera'), ('direccion', 'Área de Dirección'), ('abastecimiento', 'Área de Abastecimiento'), ('coordinacion', 'Área de Coordinación')], default='operativa', max_length=50, verbose_name='Tipo de área')),
                ('es_area_base', models.BooleanField(default=False, help_text='Indica si esta área fue creada automáticamente como área base (Abastecimiento/Finanzas).', verbose_name='¿Es área base?')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la empresa')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo de contacto')),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del contacto')),
                ('pagar_despues', models.BooleanField(default=False, verbose_name='¿Puede pagar después?')),
                ('es_lambda', models.BooleanField(default=False, verbose_name='¿Es empresa Lambda?')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado activo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['-created_at'],
            },
        ),
    ]
