# Generated by Django 5.2.7 on 2025-10-03 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('sector', models.CharField(max_length=255, verbose_name='Sector económico')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('nombre_contacto', models.CharField(max_length=255, verbose_name='Nombre del contacto')),
                ('correo_contacto', models.EmailField(max_length=254, verbose_name='Correo del contacto')),
                ('pagar_despues', models.BooleanField(default=False, verbose_name='¿Puede pagar después?')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del área')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'empresa'), name='unique_nombre_por_empresa')],
            },
        ),
    ]
