# Generated by Django 5.2.7 on 2025-10-15 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='jefe',
            field=models.ForeignKey(blank=True, help_text='Usuario jefe de esta área (debe pertenecer a la misma empresa).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Jefe de área'),
        ),
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='Empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('nombre', 'empresa'), name='unique_nombre_por_empresa'),
        ),
    ]
